# Generated by Django 5.2.10 on 2026-02-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_passwordchangetoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
