# Generated by Django 5.2.10 on 2026-02-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_telegramtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_chat_id",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
