# Generated by Django 5.2.10 on 2026-02-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_telegram_chat_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_notifications_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
